### ISSUE TITLE
Provide checkpoint function to save underlying RStudio image to docker container registry

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleComputeEngineR#123]
A lot of issues with keeping persistent packages within containers could be solved if instead of running
`docker run` for each VM restart, it instead ran `docker start` if the container already exists.  IF all else fails, make a bash script.

Re: https://github.com/cloudyr/googleComputeEngineR/commit/bc3d906d64fc12015299b6ddb672be9f7cf6e9c6?diff=split

**Comment by MarkEdmondson1234** [comment]
This is actually possible just by specifying metadata equal to the key `gce-container-declaration` but its unsupported API for now:

https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers

You can see the current meta data schema by starting an instance via gcloud then downloading its metadata

```
gcloud compute instances create-with-container busybox-vm \
   --container-image docker.io/busybox:1.27 \
   --container-command "/bin/ash" \
   --container-arg="-c" \
   --container-arg="ls -l" \
   --container-env HOME=/home,MODE=test,OWNER=admin
```

Then in R:

```r
bb <- gce_get_instance("busybox-vm", project = "mark-edmondson-gde", zone = "europe-west3-c")
cat(bb$metadata$items[bb$metadata$items$key == "gce-container-declaration","value"])
```

which gives:

```yaml
# DISCLAIMER:
# This container declaration format is not a public API and may change without
# notice. Please use gcloud command-line tool or Google Cloud Console to run
# Containers on Google Compute Engine.

spec:
  containers:
  - args:
    - -c
    - ls -l
    command:
    - /bin/ash
    env:
    - name: OWNER
      value: admin
    - name: HOME
      value: /home
    - name: MODE
      value: test
    image: docker.io/busybox:1.27
    name: busybox-vm
    securityContext:
      privileged: false
    stdin: false
    tty: false
    volumeMounts: []
  restartPolicy: Always
  volumes: []
```
