### ISSUE TITLE
Travis covr check timeout

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleComputeEngineR#26]
The tests are all successful, but the final step of uploading the results to codecov.io fails.

* Last successful build: https://travis-ci.org/cloudyr/googleComputeEngineR/builds/176420079
* First unsuccessful build: https://travis-ci.org/cloudyr/googleComputeEngineR/builds/176660349

I can't see what was introduced in to stop the timeout occuring, maybe its just going over the 20min.  The tests  themselves avoid timeout via the below in `.travis.yaml`:

```yaml
script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check googleComputeEngineR*tar.gz
after_failure:
- find *Rcheck -name '*.fail' -print -exec cat '{}' \;
```
